// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAowYwRi0yHd6l9c1Zl-46DAOGergZKnnk',
    appId: '1:310186802173:web:47b9177bc6660f81f1f794',
    messagingSenderId: '310186802173',
    projectId: 'chatapp-2c157',
    authDomain: 'chatapp-2c157.firebaseapp.com',
    storageBucket: 'chatapp-2c157.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ-iH8eAouH5NMbYBpKP49r5hkBUmn8RU',
    appId: '1:310186802173:android:cfbfa66480c0cdbbf1f794',
    messagingSenderId: '310186802173',
    projectId: 'chatapp-2c157',
    storageBucket: 'chatapp-2c157.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAET7RLeDaHSgXYjJLnQjo7Aq65CXZ4iNE',
    appId: '1:310186802173:ios:f0b21ed32e840589f1f794',
    messagingSenderId: '310186802173',
    projectId: 'chatapp-2c157',
    storageBucket: 'chatapp-2c157.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
